services:
  - type: web
    name: spucresultanalysisdashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.prod"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_toXp6TanJ0xd@ep-purple-bar-a4babm07.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: BASE_ALLOWED_HOSTS
        value: "spucresultanalysisdashboard.onrender.com"
      - key: ALLOWED_HOSTS
        value: "spucresultanalysisdashboard.onrender.com"
    postDeployCommand: python manage.py migrate