services:
  - type: web
    name: spucresultanalysisdashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: BASE_ALLOWED_HOSTS
        value: "spucresultanalysisdashboard.onrender.com"
      - key: ALLOWED_HOSTS
        value: "spucresultanalysisdashboard.onrender.com"
    postDeployCommand: "python manage.py migrate"